# tekton-trigger.yaml
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: github-listener
  namespace: tekton-pipelines
spec:
  serviceAccountName: tekton-sa
  triggers:
    - name: github-push-trigger
      bindings:
        - ref: github-push-binding
      template:
        ref: github-push-template
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: github-push-binding
  namespace: tekton-pipelines
spec:
  params:
    - name: git-repo-url
      value: "$(body.repository.clone_url)"
    - name: git-revision
      value: "$(body.head_commit.id)"

---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: github-push-template
  namespace: tekton-pipelines
spec:
  params:
    - name: git-repo-url
    - name: git-revision
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: engine-svc-pipeline-run-
      spec:
        serviceAccountName: tekton-sa
        pipelineRef:
          name: engine-svc-pipeline
        params:
          - name: repo-url
            value: $(params.git-repo-url)
          - name: revision
            value: $(params.git-revision)
